/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        border: "hsl(var(--border))",
        input: "hsl(var(--input))",
        ring: "hsl(var(--ring))",
        background: "hsl(var(--background))",
        foreground: "hsl(var(--foreground))",
        primary: {
          DEFAULT: "hsl(var(--primary))",
          foreground: "hsl(var(--primary-foreground))",
          glow: "hsl(var(--primary-glow))",
          light: "hsl(var(--primary-light))",
        },
        secondary: {
          DEFAULT: "hsl(var(--secondary))",
          foreground: "hsl(var(--secondary-foreground))",
          dark: "hsl(var(--secondary-dark))",
        },
        muted: {
          DEFAULT: "hsl(var(--muted))",
          foreground: "hsl(var(--muted-foreground))",
        },
        accent: {
          DEFAULT: "hsl(var(--accent))",
          foreground: "hsl(var(--accent-foreground))",
          light: "hsl(var(--accent-light))",
        },
        destructive: {
          DEFAULT: "hsl(var(--destructive))",
          foreground: "hsl(var(--destructive-foreground))",
        },
        card: {
          DEFAULT: "hsl(var(--card))",
          foreground: "hsl(var(--card-foreground))",
        },
        popover: {
          DEFAULT: "hsl(var(--popover))",
          foreground: "hsl(var(--popover-foreground))",
        },
        imperial: {
          yellow: "hsl(var(--imperial-yellow))",
          'yellow-fg': "hsl(var(--imperial-yellow-foreground))",
          gold: "hsl(var(--imperial-gold))",
        },
        garden: {
          green: "hsl(var(--garden-green))",
          'green-fg': "hsl(var(--garden-green-foreground))",
          light: "hsl(var(--garden-light))",
        },
        stone: {
          gray: "hsl(var(--stone-gray))",
          dark: "hsl(var(--stone-dark))",
        },
        // 扩展中国传统色
        cinnabar: "hsl(var(--cinnabar))",
        vermillion: "hsl(var(--vermillion))",
        'indigo-blue': "hsl(var(--indigo-blue))",
        celadon: "hsl(var(--celadon))",
        'ink-black': "hsl(var(--ink-black))",
        'rice-white': "hsl(var(--rice-white))",
        bronze: "hsl(var(--bronze))",
        jade: "hsl(var(--jade))",
        'lacquer-red': "hsl(var(--lacquer-red))",
        'gold-foil': "hsl(var(--gold-foil))",
        azure: "hsl(var(--azure))",
        teal: "hsl(var(--teal))",
        amber: "hsl(var(--amber))",
        violet: "hsl(var(--violet))",
        rose: "hsl(var(--rose))",
        cream: "hsl(var(--cream))",
        ivory: "hsl(var(--ivory))",
      },
      fontFamily: {
        sans: ['var(--font-sans)', 'Noto Sans SC', 'PingFang SC', 'Microsoft YaHei', 'sans-serif'],
        serif: ['var(--font-serif)', 'Noto Serif SC', 'STSong', 'SimSun', 'serif'],
      },
      borderRadius: {
        lg: "var(--radius)",
        md: "calc(var(--radius) - 2px)",
        sm: "calc(var(--radius) - 4px)",
        xl: "calc(var(--radius) + 4px)",
        '2xl': "calc(var(--radius) + 8px)",
        '3xl': "calc(var(--radius) + 12px)",
        '4xl': "2rem",
        '5xl': "2.5rem",
      },
      boxShadow: {
        'elegant': 'var(--shadow-elegant)',
        'glow': 'var(--shadow-glow)',
        'card': 'var(--shadow-card)',
        'float': 'var(--shadow-float)',
        'inner': 'var(--shadow-inner)',
        'cinnabar': 'var(--shadow-cinnabar)',
        'gold': 'var(--shadow-gold)',
        'jade': 'var(--shadow-jade)',
        'deep': 'var(--shadow-deep)',
      },
      backgroundImage: {
        'gradient-primary': 'var(--gradient-primary)',
        'gradient-imperial': 'var(--gradient-imperial)',
        'gradient-subtle': 'var(--gradient-subtle)',
        'gradient-warm': 'var(--gradient-warm)',
        'gradient-cool': 'var(--gradient-cool)',
        'gradient-hero': 'var(--gradient-hero)',
        'gradient-cinnabar': 'var(--gradient-cinnabar)',
      },
      transitionTimingFunction: {
        'smooth': 'cubic-bezier(0.4, 0, 0.2, 1)',
        'bounce': 'cubic-bezier(0.68, -0.55, 0.265, 1.55)',
        'spring': 'cubic-bezier(0.175, 0.885, 0.32, 1.275)',
        'slow': 'cubic-bezier(0.4, 0, 0.2, 1)',
        'silk': 'cubic-bezier(0.23, 1, 0.32, 1)',
      },
      animation: {
        'fade-in': 'fadeIn 0.8s ease-out',
        'slide-up': 'slideUp 0.8s ease-out',
        'scale-in': 'scaleIn 0.5s ease-out',
        'float': 'float 6s ease-in-out infinite',
        'float-slow': 'float-slow 8s ease-in-out infinite',
        'shimmer': 'shimmer 3s infinite linear',
        'pulse-glow': 'pulse-glow 3s ease-in-out infinite',
        'pulse-cinnabar': 'pulse-cinnabar 3s ease-in-out infinite',
        'rotate-slow': 'rotate-slow 20s linear infinite',
        'scale-breathe': 'scale-breathe 4s ease-in-out infinite',
        'ink-spread': 'ink-spread 0.8s cubic-bezier(0.4, 0, 0.2, 1) forwards',
        'ripple': 'ripple 0.6s ease-out forwards',
        'count-up': 'count-up 0.5s ease-out forwards',
      },
      keyframes: {
        fadeIn: {
          '0%': { opacity: '0' },
          '100%': { opacity: '1' },
        },
        slideUp: {
          '0%': { opacity: '0', transform: 'translateY(30px)' },
          '100%': { opacity: '1', transform: 'translateY(0)' },
        },
        scaleIn: {
          '0%': { opacity: '0', transform: 'scale(0.9)' },
          '100%': { opacity: '1', transform: 'scale(1)' },
        },
        float: {
          '0%, 100%': { transform: 'translateY(0px)' },
          '50%': { transform: 'translateY(-20px)' },
        },
        'float-slow': {
          '0%, 100%': { transform: 'translateY(0px) rotate(0deg)' },
          '33%': { transform: 'translateY(-12px) rotate(1deg)' },
          '66%': { transform: 'translateY(-6px) rotate(-1deg)' },
        },
        shimmer: {
          '0%': { backgroundPosition: '-1000px 0' },
          '100%': { backgroundPosition: '1000px 0' },
        },
        pulseGlow: {
          '0%, 100%': { boxShadow: '0 0 20px hsl(var(--primary-glow) / 0.4)' },
          '50%': { boxShadow: '0 0 60px hsl(var(--primary-glow) / 0.8), 0 0 100px hsl(var(--primary-glow) / 0.4)' },
        },
        pulseCinnabar: {
          '0%, 100%': { boxShadow: '0 0 20px hsl(var(--cinnabar) / 0.3)' },
          '50%': { boxShadow: '0 0 50px hsl(var(--cinnabar) / 0.7), 0 0 80px hsl(var(--cinnabar) / 0.3)' },
        },
        'rotate-slow': {
          from: { transform: 'rotate(0deg)' },
          to: { transform: 'rotate(360deg)' },
        },
        'scale-breathe': {
          '0%, 100%': { transform: 'scale(1)' },
          '50%': { transform: 'scale(1.05)' },
        },
        'ink-spread': {
          '0%': { clipPath: 'circle(0% at 50% 50%)', opacity: '0' },
          '100%': { clipPath: 'circle(100% at 50% 50%)', opacity: '1' },
        },
        ripple: {
          '0%': { transform: 'scale(0)', opacity: '0.8' },
          '100%': { transform: 'scale(4)', opacity: '0' },
        },
        'count-up': {
          from: { opacity: '0', transform: 'translateY(10px)' },
          to: { opacity: '1', transform: 'translateY(0)' },
        },
      },
      spacing: {
        '18': '4.5rem',
        '88': '22rem',
        '128': '32rem',
        '144': '36rem',
      },
      fontSize: {
        'xs': ['0.75rem', { lineHeight: '1rem' }],
        'sm': ['0.875rem', { lineHeight: '1.25rem' }],
        'base': ['1rem', { lineHeight: '1.5rem' }],
        'lg': ['1.125rem', { lineHeight: '1.75rem' }],
        'xl': ['1.25rem', { lineHeight: '1.75rem' }],
        '2xl': ['1.5rem', { lineHeight: '2rem' }],
        '3xl': ['1.875rem', { lineHeight: '2.25rem' }],
        '4xl': ['2.25rem', { lineHeight: '2.5rem' }],
        '5xl': ['3rem', { lineHeight: '1' }],
        '6xl': ['3.75rem', { lineHeight: '1' }],
        '7xl': ['4.5rem', { lineHeight: '1' }],
        '8xl': ['6rem', { lineHeight: '1' }],
        '9xl': ['8rem', { lineHeight: '1' }],
      },
      backdropBlur: {
        xs: '2px',
      },
      scale: {
        '98': '0.98',
        '102': '1.02',
        '103': '1.03',
      },
      zIndex: {
        '60': '60',
        '70': '70',
        '80': '80',
        '90': '90',
        '100': '100',
      },
    },
  },
  plugins: [],
}
